baseURL = "https://jameskaois.com/"   # update before deploy
title = "James Cao"
theme = "PaperMod"
defaultContentLanguage = "en"
enableRobotsTXT = true
[pagination]
  pagerSize = 10
enableRobotsTXT = true
[caches]
  [caches.images]
    dir = ':cacheDir/images'
# pretty URLs
uglyURLs = false

# syntax highlighting
[markup]
  [markup.highlight]
    noClasses = false
    guessSyntax = true
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true


# site params (PaperMod)
[params]
  env = "production"
  ShowReadingTime = true
  ShowShareButtons = false
  ShowPostNavLinks = true
  ShowBreadCrumbs = true
  ShowCodeCopyButtons = true
  defaultTheme = "dark"
  disableThemeToggle = true
  ShowPostCover = true
  ShowPostCoverInList = true
  ShowPostCoverInSingle = true
  description = "James Cao – Cybersecurity Blog, Cheatsheets & Notes"
  images = ["images/avatar.jpg"]

[sitemap]
  changefreq = "weekly"
  priority = 0.5
  filename = "sitemap.xml"

[outputs]
  home = ["HTML", "RSS", "JSON"]
  section = ["HTML", "RSS"]
  taxonomy = ["HTML", "RSS"]
  term = ["HTML", "RSS"]

[related]
threshold = 0
includeNewer = true
toLower = false

[[related.indices]]
name = "tags"
weight = 100

[[related.indices]]
name = "categories"
weight = 80

[[related.indices]]
name = "title"
weight = 30

# main menu
[menu]
  [[menu.main]]
    name = "Home"
    url = "/"
    weight = 1
    pre = "<i class='fa-solid fa-house'></i>"

  [[menu.main]]
    name = "My Home Lab"
    url = "/homelab/"
    weight = 2
    pre = "<i class='fa-solid fa-server'></i>"

  [[menu.main]]
    name = "Tags"
    url = "/tags/"
    weight = 3
    pre = "<i class='fa-solid fa-tags'></i>"

  [[menu.main]]
    name = "Portfolio"
    url = "/portfolio/"
    weight = 4
    pre = "<i class='fa-solid fa-briefcase'></i>"

  [[menu.main]]
    name = "Cheatsheet"
    url = "/cheatsheet/"
    weight = 5
    pre = "<i class='fa-solid fa-book'></i>"
