baseURL = "https://jameskaois.github.io/my-website/"   # update before deploy
title = "James Cao"
theme = "PaperMod"
defaultContentLanguage = "en"
[pagination]
  pagerSize = 10
enableRobotsTXT = true

# pretty URLs
uglyURLs = false

# syntax highlighting
[markup]
  [markup.highlight]
    noClasses = false
    guessSyntax = true

# site params (PaperMod)
[params]
  env = "production"
  ShowReadingTime = true
  ShowShareButtons = false
  ShowPostNavLinks = true
  ShowBreadCrumbs = true
  ShowCodeCopyButtons = true
  defaultTheme = "dark"
  disableThemeToggle = true
  ShowPostCover = true
  ShowPostCoverInList = true
  ShowPostCoverInSingle = true

  # home info card

# main menu
[menu]
  [[menu.main]]
    name = "Home"
    url = "/"
    weight = 1
    pre = "<i class='fa-solid fa-house'></i>"

  [[menu.main]]
    name = "My Home Lab"
    url = "/homelab/"
    weight = 2
    pre = "<i class='fa-solid fa-server'></i>"

  [[menu.main]]
    name = "Tags"
    url = "/tags/"
    weight = 3
    pre = "<i class='fa-solid fa-tags'></i>"

  [[menu.main]]
    name = "Portfolio"
    url = "/portfolio/"
    weight = 4
    pre = "<i class='fa-solid fa-briefcase'></i>"

  [[menu.main]]
    name = "Cheatsheet"
    url = "/cheatsheet/"
    weight = 5
    pre = "<i class='fa-solid fa-book'></i>"
